Update image builder to create a valid iamge for use with the bootrom
git-svn-id: http://casvn/svn/octeon/bdk/branches/thunder@102377 c83883e8-9f28-0410-baf1-f2025811e16a

diff --git a/bin/bdk-update-all b/bin/bdk-update-all
--- a/bin/bdk-update-all
+++ b/bin/bdk-update-all
@@ -2,19 +2,28 @@
 
 if [ "${BDK_ROOT}" = "" ]
 then
-    echo "The BDK_ROOT environment variable is not set"
+    echo "ERROR: The BDK_ROOT environment variable is not set"
     exit 1
 fi
 
 DIR=${BDK_ROOT}/target-bin
+STAGE1=${DIR}/bdk-xmodem-load.bin
+
+if [ `stat -c %s ${STAGE1}` -gt 196608 ]
+then
+    echo "ERROR: Stage1 image must be 192KB or less"
+    exit 1
+fi
 
 #
 # Create the first stage boot image
+# 1) 64KB unused by Thunder
+# 2) 64KB of CVM_CLIB header
+# 3) 192KB of image
 #
-echo -n CVM_CLIB > ${DIR}/stage1-header.tmp
-cat ${DIR}/stage1-header.tmp /dev/zero | dd of=${DIR}/bdk-stage1.bin bs=256 count=1 > /dev/null 2>&1
-rm ${DIR}/stage1-header.tmp
-cat ${DIR}/bdk-xmodem-load.bin >> ${DIR}/bdk-stage1.bin
+cat /dev/zero | head -q -c 64K > ${DIR}/bdk-stage1.bin
+echo -n CVM_CLIB | cat - /dev/zero | head -q -c 64K >> ${DIR}/bdk-stage1.bin
+cat ${DIR}/bdk-xmodem-load.bin /dev/zero | head -q -c 192K >> ${DIR}/bdk-stage1.bin
 
 #
 # Update the Lua filesystems in the images
@@ -28,12 +37,8 @@ ${BDK_ROOT}/bin/bdk-update-romfs ${DIR}/bdk-network-perf-cn88xx.bin ${DIR}/origi
 # Create combined boot images for CN78XX
 #
 # CN88XX - BDK boot from eMMC
-cat ${DIR}/bdk-stage1.bin /dev/zero | dd of=${DIR}/bdk-boot-emmc-cn88xx.bin bs=1024 count=192 > /dev/null 2>&1
-cat ${DIR}/bdk-cn88xx.bin >> ${DIR}/bdk-boot-emmc-cn88xx.bin
+cat ${DIR}/bdk-stage1.bin ${DIR}/bdk-cn88xx.bin > ${DIR}/bdk-boot-emmc-cn88xx.bin
 
 # CN88XX - BDK boot from SPI
-cat ${DIR}/bdk-stage1.bin /dev/zero | dd of=${DIR}/bdk-boot-spi-cn88xx.bin bs=1024 count=192 > /dev/null 2>&1
-cat ${DIR}/bdk-cn88xx.bin >> ${DIR}/bdk-boot-spi-cn88xx.bin
+cat ${DIR}/bdk-stage1.bin ${DIR}/bdk-cn88xx.bin > ${DIR}/bdk-boot-spi-cn88xx.bin
 
-# CN88XX - Chip screen boot from NOR
-# Already created above as the chip screen directly boots from NOR
