Add make rules to generate bdk-node1.bin, used for software init of CCPI on the second node
git-svn-id: http://casvn/svn/octeon/bdk/branches/thunder@114846 c83883e8-9f28-0410-baf1-f2025811e16a

diff --git a/bdk-boot/Makefile b/bdk-boot/Makefile
--- a/bdk-boot/Makefile
+++ b/bdk-boot/Makefile
@@ -2,6 +2,12 @@ include $(BDK_ROOT)/libbdk/bdk.mk
 
 DIR=$(BDK_ROOT)/target-bin
 
+.PHONY: all
+all: ${DIR}/bdk.bin ${DIR}/bdk-node1.bin
+
+#
+# Rules for node 0 boot stub
+#
 ${DIR}/bdk.bin: bdk.bin
 	cp bdk.bin ${DIR}/bdk.bin
 
@@ -28,6 +34,30 @@ bdk.bin: stage1.bin stage2.bin
 diagnostics: diagnostics.o $(BDK_ROOT)/libbdk/libbdk.a
 boot-stub: boot-stub.o $(BDK_ROOT)/libbdk/libbdk.a
 
+#
+# Rules for node 1 boot stub
+#
+${DIR}/bdk-node1.bin: bdk-node1.bin
+	cp bdk-node1.bin ${DIR}/bdk-node1.bin
+
+boot-stub-node1: BDK_LINK_ADDRESS=0x10000000000
+boot-stub-node1: boot-stub.o $(BDK_ROOT)/libbdk/libbdk.a
+	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
+
+bdk-node1.bin: boot-stub-node1.bin
+	if [ `stat -c %s $^` -gt 196608 ]; then echo "ERROR: $^ image must be 192KB or less";exit 1;fi
+	${BDK_ROOT}/bin/bdk-update-romfs stage1-node1.bin boot-stub-node1.bin
+	#
+	# 1) 64KB unused by Thunder
+	cat /dev/zero | head -q -c 65536 > $@
+	# 2) 64KB of CVM_CLIB header
+	echo -n CVM_CLIB | cat - /dev/zero | head -q -c 65536 >> $@
+	# 3) 192KB of boot-stub image (non-trusted)
+	cat stage1-node1.bin /dev/zero | head -q -c 196608 >> $@
+	# 4) 192KB of boot-stub image (trusted)
+	cat stage1-node1.bin /dev/zero | head -q -c 196608 >> $@
+	rm stage1-node1.bin
+
 clean:
-	rm -f *.o *.map *.bin boot-stub diagnostics ${DIR}/bdk.bin
+	rm -f *.o *.map *.bin boot-stub boot-stub-node1 diagnostics ${DIR}/bdk.bin ${DIR}/bdk-node1.bin
 
